#!/usr/bin/env python
# coding: utf-8

"""
Copyright 2015 SYSTRAN Software, Inc. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""


class TranslationStatus(object):
    """
    NOTE: This class is auto generated by the systran code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        """
        Systran model

        :param dict systran_types: The key is attribute name and the value is attribute type.
        :param dict attribute_map: The key is attribute name and the value is json key in definition.
        """
        self.systran_types = {
            'error': 'ErrorResponse',
            'batch_id': 'str',
            'cancelled': 'bool',
            'created_at': 'float',
            'description': 'str',
            'expire_at': 'float',
            'finished_at': 'float',
            'finished_steps': 'int',
            'status': 'str',
            'total_steps': 'int'
        }

        self.attribute_map = {
            'error': 'error',
            'batch_id': 'batchId',
            'cancelled': 'cancelled',
            'created_at': 'createdAt',
            'description': 'description',
            'expire_at': 'expireAt',
            'finished_at': 'finishedAt',
            'finished_steps': 'finishedSteps',
            'status': 'status',
            'total_steps': 'totalSteps'
        }
        
        # Error of the request
        self.error = None  # ErrorResponse
        
        # Batch Identifier
        self.batch_id = None  # str
        
        # Is the request cancelled
        self.cancelled = None  # bool
        
        # Creation time of the request (ms since the Epoch)
        self.created_at = None  # float
        
        # Description
        self.description = None  # str
        
        # Expiration time of the request (ms since the Epoch)
        self.expire_at = None  # float
        
        # Completion time of the request (ms since the Epoch)
        self.finished_at = None  # float
        
        # Number of finished steps
        self.finished_steps = None  # int
        
        # Status of the request
        self.status = None  # str
        
        # Number of steps to complete
        self.total_steps = None  # int
        

    def __repr__(self):
        properties = []
        for p in self.__dict__:
            if p != 'systran_types' and p != 'attribute_map':
                properties.append('{prop}={val!r}'.format(prop=p, val=self.__dict__[p]))

        return '<{name} {props}>'.format(name=__name__, props=' '.join(properties))


